import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#fbf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#fbf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f0",
        "surface-container": "#efeeeb",
        "surface-container-high": "#eae8e5",
        "surface-container-highest": "#e4e2df",
        "surface-variant": "#e4e2df",
        "surface-tint": "#216868",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#3f4948",
        "inverse-surface": "#30312f",
        "inverse-on-surface": "#f2f0ed",
        "inverse-primary": "#90d2d1",
        outline: "#6f7978",
        "outline-variant": "#bfc8c8",
        background: "#fbf9f6",
        "on-background": "#1b1c1a",

        primary: "#004343",
        "on-primary": "#ffffff",
        "primary-container": "#0f5c5c",
        "on-primary-container": "#90d2d1",
        "primary-fixed": "#aceeee",
        "primary-fixed-dim": "#90d2d1",
        "on-primary-fixed": "#002020",
        "on-primary-fixed-variant": "#004f50",

        secondary: "#904d00",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffa454",
        "on-secondary-container": "#713b00",
        "secondary-fixed": "#ffdcc3",
        "secondary-fixed-dim": "#ffb77d",
        "on-secondary-fixed": "#2f1500",
        "on-secondary-fixed-variant": "#6e3900",

        tertiary: "#7b0807",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#9d241c",
        "on-tertiary-container": "#ffb3a9",
        "tertiary-fixed": "#ffdad5",
        "tertiary-fixed-dim": "#ffb4aa",
        "on-tertiary-fixed": "#410001",
        "on-tertiary-fixed-variant": "#8c1712",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["Manrope", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        "display-lg": ["Manrope", "system-ui", "sans-serif"],
        "headline-lg": ["Manrope", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "system-ui", "sans-serif"],
        "title-md": ["Manrope", "system-ui", "sans-serif"],
        "body-lg": ["Manrope", "system-ui", "sans-serif"],
        "body-md": ["Manrope", "system-ui", "sans-serif"],
        "label-caps": ["Manrope", "system-ui", "sans-serif"],
        "stat-number": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "stat-number": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
      spacing: {
        base: "8px",
        "container-padding-mobile": "16px",
        "container-padding-desktop": "40px",
        gutter: "24px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      transitionTimingFunction: {
        out: "cubic-bezier(0.23, 1, 0.32, 1)",
        "in-out-strong": "cubic-bezier(0.77, 0, 0.175, 1)",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-up": "fade-up 300ms cubic-bezier(0.23, 1, 0.32, 1) forwards",
      },
    },
  },
  plugins: [],
};
export default config;
