FROM node:20-alpine

RUN addgroup -g 1001 -S nodejs && adduser -S node -u 1001

WORKDIR /workspace

COPY package.json ./
COPY apps/mobile/package.json ./apps/mobile/package.json

RUN npm install --workspace apps/mobile --include-workspace-root=false

COPY apps/mobile ./apps/mobile

WORKDIR /workspace/apps/mobile

USER node

EXPOSE 8081
CMD ["npm", "run", "dev"]
